import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { MouseEventHandler } from "react";
import { useContext, useState, useEffect, useRef } from "react";

export default function Home() {
  const timeInput = useRef<HTMLInputElement | null>(null);

  const [first, setFirst] = useState("");

  // function HandlerOnClick() {
  //   if (timeInput.current?.checkValidity()) {
  //     timeInput.current.setCustomValidity(
  //       "Time set must be at least 5 minutes from now"
  //     );
  //     timeInput.current.reportValidity();
  //   } else {
  //     timeInput.current.setCustomValidity("dfdfddf");
  //   }
  // }
  function ValidateLink() {
    if (timeInput.current?.checkValidity()) {
      if (timeInput.current?.validity.patternMismatch) {
        timeInput.current?.setCustomValidity("insert a valid Amazon Link");
      }
    } else {
      timeInput.current?.setCustomValidity("insert a valid Amazon Link");
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input type="text" ref={timeInput} />
        <button onClick={ValidateLink}> Click to validate</button>
        {first}
      </main>
    </>
  );
}
